export const Images = {
  sign_in_bg: require('../../assets/sign_in_bg.png'),
  main_bg: require('../../assets/main_bg.png'),
  undersea_icon: require('../../assets/undersea_small.png'),
  undersea: require('../../assets/undersea_big.png'),
  profil_icon: require('../../assets/profil_icon.png'),
  city_tab: require('../../assets/tab_city.png'),
  attack_tab: require('../../assets/tab_attack.png'),
  upgrade_icon: require('../../assets/profil_icon.png'),
  fight_icon: require('../../assets/profil_icon.png'),
  bevy_tab: require('../../assets/tab_units.png'),
  home_tab: require('../../assets/tab_home.png'),
  star_icon: require('../../assets/profil_icon.png'),
  shark_icon: require('../../assets/shark.png'),
  seal_icon: require('../../assets/seal.png'),
  seahorse_icon: require('../../assets/seahorse.png'),
  shell_icon: require('../../assets/shell.png'),
  coral_icon: require('../../assets/coral.png'),
  flow_control_icon: require('../../assets/flow_control_icon.png'),
  reef_castle_icon: require('../../assets/reef_castle_icon.png'),
  flow_control: require('../../assets/flow_control.png'),
  reef_castle: require('../../assets/reef_castle.png'),
  profil: require('../../assets/profil.png'),
  tractor: require('../../assets/tractor.png'),
  plus: require('../../assets/profil_icon.png'),
  minus: require('../../assets/profil_icon.png'),
}
