export const Images = {
  sign_in_bg: require('../../assets/sign_in_bg.png'),
  main_bg: require('../../assets/main_bg.png'),
  undersea_icon: require('../../assets/undersea_small.png'),
  undersea: require('../../assets/undersea_big.png'),
  profil_icon: require('../../assets/profil_icon.png'),
  city_tab: require('../../assets/tab_city.png'),
  attack_tab: require('../../assets/tab_attack.png'),
  upgrade_icon: require('../../assets/profil_icon.png'),
  fight_icon: require('../../assets/profil_icon.png'),
  bevy_tab: require('../../assets/tab_units.png'),
  home_tab: require('../../assets/tab_home.png'),
  profil: require('../../assets/profil.png'),
  plus: require('../../assets/plus.png'),
  minus: require('../../assets/minus.png'),
  edit: require('../../assets/edit.png'),
  back_arrow: require('../../assets/arrow_left.png'),
  up_arrow: require('../../assets/caret_up.png'),
  down_arrow: require('../../assets/caret_down.png'),
  done: require('../../assets/done.png'),
}
