export const Screens = {
  Login: 'Login',
  Registration: 'Registration',
  Main: 'Kezdőlap',
  City: 'Városom',
  Buildings: 'Épületek',
  AttackFirst: 'Támadás',
  AttackSecond: 'AttackSecond',
  Upgrades: 'Fejlesztések',
  Fight: 'Csapatok',
  Bevy: 'Sereg',
  Profil: 'Profils',
  Ranking: 'Ranking',
  Exploration: 'Felfedezők',
  Unit: 'Csapataim',
}
