export const Strings = {
  login: 'Belépés',
  registration: 'Regisztráció',
  user_name: 'Felhasználónév',
  password: 'Jelszó',
  password_again: 'Jelszó megerősítése',
  login_text: 'Nincs még fiókod?',
  registration_text: 'Már van fiókod?',
  login_replace_text: 'Regisztrálj',
  registration_replace_text: 'Lépj be',
  city_name_what_you_bulid: 'A városod neve, amit építesz',
  profil: 'Profil',
  buildings: 'Épületek',
  attack: 'Támadás',
  upgrades: 'Fejlesztések',
  fight: 'Csapataim',
  bevy: 'Sereg',
  round: 'kör',
  place: 'hely',
  buildings_title: 'Jelöld ki, amelyiket szeretnéd megvenni.',
  buildings_description: 'Egyszerre csak egy épület épülhet!',
  upgrades_title: 'Jelöld ki, amelyiket szeretnéd megvenni.',
  upgrades_description:
    'Jelöld ki, amelyiket szeretnéd megvenni. Minden fejlesztés 15 kört vesz igénybe, egyszerre csak egy dolog fejleszthető és minden csak egyszer fejleszthető ki (nem lehet két kombájn).',
  attack_first_title: '1. Lépés',
  attack_first_description: 'Jelöld ki, kit szeretnél megtámadni:',
  attack_second_title: '2. Lépés',
  attack_second_description: 'Állítsd be, kiket küldesz harcba:',
  bevy_title: 'Jelöld ki, amelyiket szeretnéd:',
  ranking: 'Ranglista',
  log_out: 'Kijelentkezés',
  piece: 'db',
  pearl_per_piece: 'Gyöngy/db',
  buy: 'Megveszem',
  owned: 'Birtokodban',
  attack_per_defense: 'Támadás/Védekezés',
  pay: 'Zsold (kör/példány)',
  supply: 'Ellátmány (kör/példány)',
  price: 'Ár',
  coral: 'Korall',
  pearl: 'Gyöngy',
  next: 'Tovább',
  back: 'vissza',
  copy: 'példány',
  attack_button: 'Megtámadom!',
}
